// src/components/react/SingleComponentCounter.tsx
import { useState } from "react";

const SingleComponentCounter = () => {
  const [count, setCount] = useState(0);

  return (
    <div>
      <h1>Single Component Counter</h1>
      <p>Count: {count}</p>
      <button className="btn btn-primary" onClick={() => setCount(count + 1)}>
        Increment
      </button>
    </div>
  );
};

export default SingleComponentCounter;

// src/components/vue/SingleComponentCounter.vue
<template>
  <div>
    <h1>Single Component Counter</h1>
    <p>{{ count }}</p>
    <button @click="count++" class="btn btn-primary">Increment</button>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

const count = ref(0);
// const incrementInsideScript = () => count.value++;
</script>
