// src/components/react/ModularCounter/ModularCounter.tsx
import { useState } from "react";
import CounterDisplayer from "./CounterDisplayer";
import CounterIncrementer from "./CounterIncrementer";

const ModularCounter = () => {
  const [count, setCount] = useState(0);

  return (
    <div>
      <h1>Modular Counter</h1>
      <CounterDisplayer count={count} />
      <CounterIncrementer setCount={setCount} />
    </div>
  );
};

export default ModularCounter;

// src/components/vue/ModularCounter/ModularCounter.vue
<template>
  <div>
    <h1>Modular Counter</h1>
    <CounterDisplayer :count="count" />
    <CounterIncrementer :increment="() => count++" />
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import CounterDisplayer from "./CounterDisplayer.vue";
import CounterIncrementer from "./CounterIncrementer.vue";

const count = ref(0);

</script>
